export * from './page1/Page1';
export * from './page2/Page2';
export * from './contact-details/ContactDetails';
export * from './portal/Portal';
export * from './quote/Quote';
export * from './step/Step';
export * from './submit/Submit';
export * from './thank-you/ThankYou';
export * from './todoPage/TodoPage';